export const enum ACTIONS_TYPE {
  TOGGLE_IS_AUTH = 'TOGGLE_IS_AUTH',
  TRIPS_CARD = 'TRIPS_CARD',
  LOAD_IMAGE = 'LOAD_IMAGE',
  SELECTED_FILTERS = 'SELECTED_FILTERS',
  TOGGLE_IS_DIRECT = 'TOGGLE_IS_DIRECT',
  ERROR_ALERT = 'ERROR_ALERT',
}
